# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    fos_user.doctrine_registry:
        alias: doctrine
    my_user_provider:
        class: RocketSeller\TwoPickBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, linkedin: linkedin_id}]
    registration_confirm:
        class: RocketSeller\TwoPickBundle\Listener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    app.form.registration:
        class: RocketSeller\TwoPickBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    wsse.security.authentication.provider:
        class: RocketSeller\TwoPickBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - "" # User Provider
            - "%kernel.cache_dir%/security/nonces"
            - "" # token lifetime
        public: false

    wsse.security.authentication.listener:
        class: RocketSeller\TwoPickBundle\Security\Authentication\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        public: false

    send_sms:
        class: RocketSeller\TwoPickBundle\Controller\SmsController

    validate.user.onload:
        class: RocketSeller\TwoPickBundle\Listener\ValidateUserOnloadListener
        arguments: [@router, @doctrine.orm.entity_manager]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.symplifica_voter:
        class: RocketSeller\TwoPickBundle\Security\Voter\SymplificaVoter
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: security.voter }
    fos_user.listener.email_confirmation:
        class: RocketSeller\TwoPickBundle\Listener\EmailConfirmationListener
        arguments: ["@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
    symplifica.mailer.twig_swift:
        class: RocketSeller\TwoPickBundle\Mailer\TwigSwiftMailer
        arguments:
            - '@mailer'
            - '@router'
            - '@twig'
            -
                template:
                    confirmation: '%fos_user.registration.confirmation.template%'
                    resetting: '%fos_user.resetting.email.template%'
                    welcome: 'FOSUserBundle:Registration:email-welcome.txt.twig'
                    reminder: 'FOSUserBundle:Registration:recuerdatos.txt.twig'
                    help:     'FOSUserBundle:Registration:email-contact.txt.twig'
                    daviplata: 'FOSUserBundle:Registration:crearDaviplata.txt.twig'
                    oneday: 'FOSUserBundle:Registration:diahabil.txt.twig'
                    diashabiles: 'FOSUserBundle:Registration:3diashabiles.txt.twig'
                    backoffice_warning: 'FOSUserBundle:Registration:backofficeWarning.txt.twig'
                    backval: 'FOSUserBundle:Registration:validation-user.txt.twig'
                    remindNovelty: 'FOSUserBundle:Registration:payRecorder.txt.twig'
                    lastRemindNovelty: 'FOSUserBundle:Registration:lastPayRecorder.txt.twig'
                    log: 'FOSUserBundle:SendEmail:logEmail.html.twig'
                    reminderDaviplata : 'FOSUserBundle:Registration:daviplataRecorder.txt.twig'
                    succesRecollect : 'FOSUserBundle:Pay:exitoRecaudoEmail.txt.twig'
                    failRecollect : 'FOSUserBundle:Pay:falloRecaudoEmail.txt.twig'
                    regectionCollect : 'FOSUserBundle:Backoffice:rejectionTransactionLog.txt.twig'
                    regectionDispersion : 'FOSUserBundle:Backoffice:rejectionDispersionLog.txt.twig'
                    succesDispersion : 'FOSUserBundle:Pay:exitoDispersionEmail.txt.twig'
                    failDispersion : 'FOSUserBundle:Pay:falloDispersionEmail.txt.twig'
                    validatePayMethod : 'FOSUserBundle:Pay:validatePaymentMethodEmail.txt.twig'
                    transactionRejected : 'FOSUserBundle:Pay:payRejectedEmail.txt.twig'
                    transactionAcepted : 'FOSUserBundle:Pay:succesfulTransaction.txt.twig'
                    liquidation: 'FOSUserBundle:BackOffice:liquidationProcess.txt.twig'
                    appDownload: 'FOSUserBundle:Registration:descargaApp.txt.twig'

                from_email:
                  confirmation: '%fos_user.registration.confirmation.from_email%'
                  resetting: '%fos_user.resetting.email.from_email%'
    app.symplifica_utils:
        class: RocketSeller\TwoPickBundle\Controller\UtilsController
    app.symplifica_chrons:
        class: RocketSeller\TwoPickBundle\Controller\ChronServerRestController
        arguments: ["@service_container"]