# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    fos_user.doctrine_registry:
        alias: doctrine
    my_user_provider:
        class: RocketSeller\TwoPickBundle\Security\Core\User\FOSUBUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: [@fos_user.user_manager,{facebook: facebook_id, google: google_id, linkedin: linkedin_id}]
    registration_confirm:
        class: RocketSeller\TwoPickBundle\Listener\RegistrationConfirmListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }
    app.form.registration:
        class: RocketSeller\TwoPickBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    wsse.security.authentication.provider:
        class: RocketSeller\TwoPickBundle\Security\Authentication\Provider\WsseProvider
        arguments:
            - "" # User Provider
            - "%kernel.cache_dir%/security/nonces"
            - "" # token lifetime
        public: false

    wsse.security.authentication.listener:
        class: RocketSeller\TwoPickBundle\Security\Authentication\Firewall\WsseListener
        arguments: ["@security.token_storage", "@security.authentication.manager"]
        public: false

    send_sms:
        class: RocketSeller\TwoPickBundle\Controller\SmsController

    validate.user.onload:
        class: RocketSeller\TwoPickBundle\Listener\ValidateUserOnloadListener
        arguments: [@router, @doctrine.orm.entity_manager]
        calls:
            - [ setContainer, [ @service_container ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.symplifica_voter:
        class: RocketSeller\TwoPickBundle\Security\Voter\SymplificaVoter
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: security.voter }
    fos_user.listener.email_confirmation:
        class: RocketSeller\TwoPickBundle\Listener\EmailConfirmationListener
        arguments: ["@fos_user.mailer", "@fos_user.util.token_generator", "@router", "@session"]
        tags:
            - { name: kernel.event_subscriber }
    symplifica.mailer.twig_swift:
        class: RocketSeller\TwoPickBundle\Mailer\TwigSwiftMailer
        arguments:
            - '@mailer'
            - '@router'
            - '@twig'
            -
                template:
                    confirmation: '%fos_user.registration.confirmation.template%'
                    resetting: '%fos_user.resetting.email.template%'
                    welcome: 'FOSUserBundle:EmailTemplates:email-welcome.txt.twig'
                    reminder: 'FOSUserBundle:EmailTemplates:recuerdatos.txt.twig'
                    help:     'FOSUserBundle:EmailTemplates:email-contact.txt.twig'
                    daviplata: 'FOSUserBundle:EmailTemplates:crearDaviplata.txt.twig'
                    oneday: 'FOSUserBundle:EmailTemplates:diahabil.txt.twig'
                    diashabiles: 'FOSUserBundle:EmailTemplates:3diashabiles.txt.twig'
                    backoffice_warning: 'FOSUserBundle:EmailTemplates:backofficeWarning.txt.twig'
                    backval: 'FOSUserBundle:EmailTemplates:validation-user.txt.twig'
                    remindNovelty: 'FOSUserBundle:EmailTemplates:payRecorder.txt.twig'
                    lastRemindNovelty: 'FOSUserBundle:EmailTemplates:lastPayRecorder.txt.twig'
                    log: 'FOSUserBundle:EmailTemplates:logEmail.html.twig'
                    reminderDaviplata : 'FOSUserBundle:EmailTemplates:daviplataRecorder.txt.twig'
                    succesRecollect : 'FOSUserBundle:EmailTemplates:exitoRecaudoEmail.txt.twig'
                    failRecollect : 'FOSUserBundle:EmailTemplates:falloRecaudoEmail.txt.twig'
                    regectionCollect : 'FOSUserBundle:EmailTemplates:rejectionTransactionLog.txt.twig'
                    regectionDispersion : 'FOSUserBundle:EmailTemplates:rejectionDispersionLog.txt.twig'
                    succesDispersion : 'FOSUserBundle:EmailTemplates:exitoDispersionEmail.txt.twig'
                    failDispersion : 'FOSUserBundle:EmailTemplates:falloDispersionEmail.txt.twig'
                    validatePayMethod : 'FOSUserBundle:EmailTemplates:validatePaymentMethodEmail.txt.twig'
                    transactionRejected : 'FOSUserBundle:EmailTemplates:payRejectedEmail.txt.twig'
                    transactionAcepted : 'FOSUserBundle:EmailTemplates:succesfulTransaction.txt.twig'
                    liquidation: 'FOSUserBundle:EmailTemplates:liquidationProcess.txt.twig'
                    appDownload: 'FOSUserBundle:EmailTemplates:descargaApp.txt.twig'
                    descubrir: 'FOSUserBundle:EmailTemplates:descubreSymplifica.txt.twig'
                    supplies: 'FOSUserBundle:EmailTemplates:dotacion.txt.twig'
                    waiting: 'FOSUserBundle:EmailTemplates:estamosEsperando.txt.twig'
                    contractFinishReminder: 'FOSUserBundle:EmailTemplates:fechaTerminaContrato.txt.twig'
                    cesantCharges: 'FOSUserBundle:EmailTemplates:interesesCesantias.txt.twig'
                    cesantPayment: 'FOSUserBundle:EmailTemplates:pagoCesantias.txt.twig'
                    bonus: 'FOSUserBundle:EmailTemplates:pagoPrima.txt.twig'
                    clientRecovery: 'FOSUserBundle:EmailTemplates:recuperarCliente.txt.twig'
                    risks: 'FOSUserBundle:EmailTemplates:riesgoNoPago.txt.twig'
                    contractFinish: 'FOSUserBundle:EmailTemplates:terminacionContrato.txt.twig'
                    contractAttachmentEmail: 'FOSUserBundle:EmailTemplates:contractAttachmentEmail.txt.twig'
                    docsValidated: 'FOSUserBundle:EmailTemplates:employerDocumentsValidated.txt.twig'
                    docsError: 'FOSUserBundle:EmailTemplates:employerDocumentsErrorValidation.txt.twig'
                    employeeDocsError: 'FOSUserBundle:EmailTemplates:employeeDocumentsErrorValidation.txt.twig'
                    employeeDocsValidated: 'FOSUserBundle:EmailTemplates:employeeDocumentsValidated.txt.twig'
                    notRegisteredUserApp: 'FOSUserBundle:EmailTemplates:notRegisteredUserApp.txt.twig'
                    helpTransaction: 'FOSUserBundle:EmailTemplates:helpTransaction.txt.twig'
                    stuckRegistration: 'FOSUserBundle:EmailTemplates:stuck_registration_wizard.txt.twig'
                    primaReminder: 'FOSUserBundle:EmailTemplates:primaReminder.txt.twig'
                    reportVacacionesXD: 'FOSUserBundle:EmailTemplates:reportVacacionesXD.txt.twig'
                    endContractAdvice: 'FOSUserBundle:EmailTemplates:endContract.txt.twig'
                    minimumSalaryAdjust: 'FOSUserBundle:EmailTemplates:minimumSalaryAdjust.txt.twig'
                    sendBackLandingInfo: 'FOSUserBundle:EmailTemplates:landingBackInfo.txt.twig'
                    promoReferred5days: 'FOSUserBundle:EmailTemplates:promocionReferidos5dias.txt.twig'
                    promoReferred15days: 'FOSUserBundle:EmailTemplates:promocionReferidos15dias.txt.twig'
                    twoMonthsRegistration: 'FOSUserBundle:EmailTemplates:twoMonthsWithoutRegistration.txt.twig'
                    noRegisterFacebook: 'FOSUserBundle:EmailTemplates:noRegisterFacebook.txt.twig'
                    noRegisterLanding: 'FOSUserBundle:EmailTemplates:noRegisterLanding.txt.twig'
                    testAnalytics: 'FOSUserBundle:EmailTemplates:testAnalytics.txt.twig'
                    errorInBanckAccountRegistration: 'FOSUserBundle:EmailTemplates:errorInBanckAccountRegistration.txt.twig'
                    severancesAdvice: 'FOSUserBundle:EmailTemplates:avisoPagoCesantias.txt.twig'
                from_email:
                  confirmation: '%fos_user.registration.confirmation.from_email%'
                  resetting: '%fos_user.resetting.email.from_email%'
    app.symplifica_utils:
        class: RocketSeller\TwoPickBundle\Controller\UtilsController
        arguments: ["@service_container"]
    app.symplifica_chrons:
        class: RocketSeller\TwoPickBundle\Controller\ChronServerRestController
        arguments: ["@service_container"]
    app.symplifica_push_notification:
        class: RocketSeller\TwoPickBundle\Controller\PushNotificationRestController
        arguments: ["@service_container"]
