download_documents:
    path:     /downloads/{ref}/{id}/{type}/{attach}
    defaults: { _controller: "RocketSellerTwoPickBundle:Document:downloadDocuments", attach:null }
    requirements:
        type: (pdf|html)