#Liquidation
liquidation:
    path: /
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:index }
liquidations_by_ehe:
    path: /{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:listByEhE }
liquidation_show:
    path: /show/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:show }
final_liquidation:
    path: /final/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:finalLiquidation }
final_liquidation_detail:
    path: /final/detail/{id}/{employee_id}/{period}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:finalLiquidationDetail }
generate_pdf:
    path: /generate/pdf
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:generatePdf }