#Liquidation
liquidation:
    path: /
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:index }
liquidations_by_ehe:
    path: /{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:listByEhE }
    requirements:
        id: \d+
liquidation_show:
    path: /show/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:show }
final_liquidation:
    path: /final/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:finalLiquidation }
    requirements:
        id: \d+
final_liquidation_steps:
    path: /final/{id}/{id_liq}/{step}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:finalLiquidationSteps }    
    requirements:
        id: \d+
        step: \d+
        id_liq: \d+
final_liquidation_detail:
    path: /final/detail/{id}/{employee_id}/{period}/{id_liq}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:finalLiquidationDetail }
    requirements:
        id: \d+
        employee_id: \d+
        period: \d+
        id_liq: \d+
generate_pdf:
    path: /generate/pdf
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:generatePdf }
pay_liquidation:
    path: /final/pay/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:payLiquidation }
    requirements:
        id: \d+
cartas_liquidacion:
    path: /cartas/{ref}/{id}
    defaults: { _controller: RocketSellerTwoPickBundle:Liquidation:cartasLiquidacion }
    requirements:
        ref: (renuncia|aceptacion)
        id: \d+