<?php

namespace RocketSeller\TwoPickBundle\Entity;

/**
 * NoveltyTypeFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoveltyTypeFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
