<?php

namespace RocketSeller\TwoPickBundle\Entity;

/**
 * PurchaseOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PurchaseOrdersRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * Function used to update the status of a Purchase Order
	 * @param int $id Purchase Order's id
	 * @param type $status New status
	 * @return boolean true on success / false on error
	 */
	public function updateOrderStatus(PurchaseOrders $id, PurchaseOrdersStatus $status) {

		$em = $this->getEntityManager();
		$order = $this->find($id);
		$order->setPurchaseOrdersTypePurchaseOrdersStatus($status);
		$em->flush();
	}
}