<?php

namespace RocketSeller\TwoPickBundle\Entity;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository
{
	public function getSetting(User $user, $key) {
		$setting =  $this->findOneBy(
            array(
                'userUser' => $user->getId()
            )
        );

        if($setting)
        	return $setting;
       	else {
       		$setting = new Settings();
       		$setting->setSettingKey($key);
       		$setting->setUserUser($user);
       		return $setting;
       	}
	}
}
