services:
    sonata.admin.user:
        class: RocketSeller\TwoPickBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Persons", label: "Users" }
        arguments:
            - ~
            - RocketSeller\TwoPickBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [RocketSellerTwoPickBundle]]
    sonata.admin.person:
        class: RocketSeller\TwoPickBundle\Admin\PersonAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Persons", label: "Persons" }
        arguments:
            - ~
            - RocketSeller\TwoPickBundle\Entity\Person
            - ~
        calls:
            - [ setTranslationDomain, [RocketSellerTwoPickBundle]]
    sonata.admin.beneficiary:
        class: RocketSeller\TwoPickBundle\Admin\BeneficiaryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Persons", label: "Beneficiary" }
        arguments:
            - ~
            - RocketSeller\TwoPickBundle\Entity\Beneficiary
            - ~
        calls:
            - [ setTranslationDomain, [RocketSellerTwoPickBundle]]
    sonata.admin.employer:
        class: RocketSeller\TwoPickBundle\Admin\EmployerAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Persons", label: "Employer" }
        arguments:
            - ~
            - RocketSeller\TwoPickBundle\Entity\Employer
            - ~
        calls:
            - [ setTranslationDomain, [RocketSellerTwoPickBundle]]

    rocket_seller_two_pick.admin.bank:
        class: RocketSeller\TwoPickBundle\Admin\BankAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Bank, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Other, label: Bank}

    rocket_seller_two_pick.admin.benefits:
        class: RocketSeller\TwoPickBundle\Admin\BenefitsAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Benefits, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Persons Extra, label: Benefits}

    rocket_seller_two_pick.admin.city:
        class: RocketSeller\TwoPickBundle\Admin\CityAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\City, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Other, label: City}

    rocket_seller_two_pick.admin.contract:
        class: RocketSeller\TwoPickBundle\Admin\ContractAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Contract, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Persons Extra, label: Contract}

    rocket_seller_two_pick.admin.contract_has_benefits:
        class: RocketSeller\TwoPickBundle\Admin\ContractHasBenefitsAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\ContractHasBenefits, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Persons Extra, label: Contract  Benefits}

    rocket_seller_two_pick.admin.employee_has_beneficiary:
        class: RocketSeller\TwoPickBundle\Admin\EmployeeHasBeneficiaryAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\EmployeeHasBeneficiary, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Employee, label: Employee Beneficiary}

    rocket_seller_two_pick.admin.employee:
        class: RocketSeller\TwoPickBundle\Admin\EmployeeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Employee, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Persons, label: Employee}

    rocket_seller_two_pick.admin.entity_type:
        class: RocketSeller\TwoPickBundle\Admin\EntityTypeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\EntityType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Entities, label: Entity Type}

    rocket_seller_two_pick.admin.entity:
        class: RocketSeller\TwoPickBundle\Admin\EntityAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Entity, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Entities, label: Entity}

    rocket_seller_two_pick.admin.document:
        class: RocketSeller\TwoPickBundle\Admin\DocumentAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Document, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Documents, label: Document}

    rocket_seller_two_pick.admin.department:
        class: RocketSeller\TwoPickBundle\Admin\DepartmentAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Department, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Other, label: Department}

    rocket_seller_two_pick.admin.document_type:
        class: RocketSeller\TwoPickBundle\Admin\DocumentTypeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\DocumentType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Documents, label: Document Type}

    rocket_seller_two_pick.admin.employee_has_entity:
        class: RocketSeller\TwoPickBundle\Admin\EmployeeHasEntityAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\EmployeeHasEntity, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Employee, label: Employee Entitie}

    rocket_seller_two_pick.admin.employer_has_employee:
        class: RocketSeller\TwoPickBundle\Admin\EmployerHasEmployeeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\EmployerHasEmployee, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Employer, label: Employer Employee}

    rocket_seller_two_pick.admin.employer_has_entity:
        class: RocketSeller\TwoPickBundle\Admin\EmployerHasEntityAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\EmployerHasEntity, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Employer, label: Employer Entity}

    rocket_seller_two_pick.admin.entity_fields:
        class: RocketSeller\TwoPickBundle\Admin\EntityFieldsAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\EntityFields, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Entities, label: Entity Fields}

    rocket_seller_two_pick.admin.novelty:
        class: RocketSeller\TwoPickBundle\Admin\NoveltyAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Novelty, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Payments, label: Novelty}

    rocket_seller_two_pick.admin.office:
        class: RocketSeller\TwoPickBundle\Admin\OfficeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Office, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Entities, label: Office}

    rocket_seller_two_pick.admin.pay:
        class: RocketSeller\TwoPickBundle\Admin\PayAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Pay, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Payments, label: Pay}

    rocket_seller_two_pick.admin.pay_method:
        class: RocketSeller\TwoPickBundle\Admin\PayMethodAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\PayMethod, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Payments, label: PayMethod}

    rocket_seller_two_pick.admin.pay_type:
        class: RocketSeller\TwoPickBundle\Admin\PayTypeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\PayType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Payments, label: PayType}

    rocket_seller_two_pick.admin.payroll:
        class: RocketSeller\TwoPickBundle\Admin\PayrollAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Payroll, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Payments, label: Payroll}

    rocket_seller_two_pick.admin.payroll_detail:
        class: RocketSeller\TwoPickBundle\Admin\PayrollDetailAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\PayrollDetail, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Payments, label: PayrollDetail}

    rocket_seller_two_pick.admin.procedure_type:
        class: RocketSeller\TwoPickBundle\Admin\ProcedureTypeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\ProcedureType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Procedures, label: ProcedureType}

    rocket_seller_two_pick.admin.product:
        class: RocketSeller\TwoPickBundle\Admin\ProductAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Products, label: Product}

    rocket_seller_two_pick.admin.action:
        class: RocketSeller\TwoPickBundle\Admin\ActionAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Action, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Actions, label: Action}

    rocket_seller_two_pick.admin.action_type:
        class: RocketSeller\TwoPickBundle\Admin\ActionTypeAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\ActionType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Actions, label: ActionType}

    rocket_seller_two_pick.admin.real_procedure:
        class: RocketSeller\TwoPickBundle\Admin\RealProcedureAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\RealProcedure, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Procedures, label: Real Procedure}

    rocket_seller_two_pick.admin.notification:
        class: RocketSeller\TwoPickBundle\Admin\NotificationAdmin
        arguments: [~, RocketSeller\TwoPickBundle\Entity\Notification, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Notification}
