tokens :
    type: rest
    resource: "RocketSellerTwoPickBundle:TokenRest"
    name_prefix: api_public_
notification :
    type: rest
    resource: "RocketSellerTwoPickBundle:NotificationRest"
    name_prefix: api_public_
employer :
    type: rest
    resource: "RocketSellerTwoPickBundle:PersonRest"
    name_prefix: api_public_
calculator :
    type: rest
    resource: "RocketSellerTwoPickBundle:CalculatorRest"
    name_prefix: api_public_
employee :
    type: rest
    resource: "RocketSellerTwoPickBundle:EmployeeRest"
    name_prefix: api_public_
purchase_orders_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:PurchaseOrdersRest"
    name_prefix: api_public_
send_email_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:SendEmailRest"
    name_prefix: api_public_
employer_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:EmployerRest"
    name_prefix: api_public_
novelty_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:NoveltyRest"
    name_prefix: api_public_
payments_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:PaymentsRest"
    name_prefix: api_public_
liquidation_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:LiquidationRest"
    name_prefix: api_public_
contract_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:ContractRest"
    name_prefix: api_public_
pay_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:PayRest"
    name_prefix: api_public_
payments_services_test:
    type: rest
    resource: "RocketSellerTwoPickBundle:PaymentsRestTest"
    name_prefix: api_plublic_
