tokens : 
    type: rest
    resource:     "RocketSellerTwoPickBundle:TokenRest"
    name_prefix:  api_public_
employer :
    type: rest
    resource:     "RocketSellerTwoPickBundle:PersonRest"
    name_prefix:  api_public_
calculator :
    type: rest
    resource:     "RocketSellerTwoPickBundle:CalculatorRest"
    name_prefix:  api_public_
employee :
    type: rest
    resource:     "RocketSellerTwoPickBundle:EmployeeRest"
    name_prefix:  api_public_
purchase_orders_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:PurchaseOrdersRest"
    name_prefix: api_public_
send_email_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:SendEmailRest"
    name_prefix: api_public_