users : 
    type: rest
    resource:     "RocketSellerTwoPickBundle:UserRest"
    name_prefix:  api_secured_
employers :
    type: rest
    resource:     "RocketSellerTwoPickBundle:EmployerRestSecured"
    name_prefix:  api_secured_
payrolls :
    type: rest
    resource:     "RocketSellerTwoPickBundle:PayrollRestSecured"
    name_prefix:  api_secured_