tokens :
    type: rest
    resource: "RocketSellerTwoPickBundle:TokenRest"
    name_prefix: api_public_
novelty :
    type: rest
    resource : "RocketSellerTwoPickBundle:NoveltyRest"
    name_prefix: api_public_
notification :
    type: rest
    resource: "RocketSellerTwoPickBundle:NotificationRest"
    name_prefix: api_public_
employer :
    type: rest
    resource: "RocketSellerTwoPickBundle:PersonRest"
    name_prefix: api_public_
calculator :
    type: rest
    resource: "RocketSellerTwoPickBundle:CalculatorRest"
    name_prefix: api_public_
employee :
    type: rest
    resource: "RocketSellerTwoPickBundle:EmployeeRest"
    name_prefix: api_public_
purchase_orders_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:PurchaseOrdersRest"
    name_prefix: api_public_
send_email_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:SendEmailRest"
    name_prefix: api_public_
employer_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:EmployerRest"
    name_prefix: api_public_
novelty_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:NoveltyRest"
    name_prefix: api_public_
payments_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:PaymentsRest"
    name_prefix: api_public_secured_
    prefix: /secured
payments_services_2:
    type: rest
    resource: "RocketSellerTwoPickBundle:Payments2Rest"
    name_prefix: api_public_secured_
    prefix: /secured
novo_payment_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:NovoPaymentRest"
    name_prefix: api_public_
ht_payment_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:HighTechRest"
    name_prefix: api_public_
datacredito_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:DataCreditoRest"
    name_prefix: api_public_secured_
    prefix: /secured
refered_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:ReferredRest"
    name_prefix: api_public_
invitation_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:InvitationRest"
    name_prefix: api_public_
liquidation_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:LiquidationRest"
    name_prefix: api_public_
contract_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:ContractRest"
    name_prefix: api_public_
pay_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:PayRest"
    name_prefix: api_public_
payments_services_test:
    type: rest
    resource: "RocketSellerTwoPickBundle:PaymentsRestTest"
    name_prefix: api_plublic_
payroll_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:PayrollRest"
    name_prefix: api_public_secured_
    prefix: /secured
payroll_method_rest:
    type: rest
    resource: "RocketSellerTwoPickBundle:PayrollMethodRest"
    name_prefix: api_public_
pila_csv_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:PilaPlainTextRest"
    name_prefix: api_plublic_secured_
    prefix: /secured
payroll_services_test:
    type: rest
    resource: "RocketSellerTwoPickBundle:PayrollRestTest"
    name_prefix: api_plublic_
registration_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:RegistrationRest"
    name_prefix: api_plublic_
resetting_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:ResettingRest"
    name_prefix: api_public_
document_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:DocumentRest"
    name_prefix: api_public_
payment_method:
    type: rest
    resource: "RocketSellerTwoPickBundle:PaymentMethodRest"
    name_prefix: api_public_
payment_express_register:
    type: rest
    resource: "RocketSellerTwoPickBundle:ExpressRegistrationRest"
    name_prefix: api_public_
subscription_services:
    type: rest
    resource: "RocketSellerTwoPickBundle:SubscriptionRest"
    name_prefix: api_public_
