users :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:UserRest"
    name_prefix:  api_secured_
employers :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:EmployerRestSecured"
    name_prefix:  api_secured_
payrolls :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:PayrollRestSecured"
    name_prefix:  api_secured_
device :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:DeviceRestSecured"
    name_prefix:  api_secured_
document :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:DocumentRestSecured"
    name_prefix:  api_secured_
pay :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:PayRestSecured"
    name_prefix:  api_secured_
backoffice :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:BackOfficeRestSecured"
    name_prefix:  api_secured_
email :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:EmailRestSecured"
    name_prefix:  api_secured_
employee :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:EmployeeRestSecured"
    name_prefix:  api_secured_
novelty :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:NoveltyRestSecured"
    name_prefix:  api_secured_
notification :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:NotificationRestSecured"
    name_prefix:  api_secured_
contract :
    type:         rest
    resource:     "RocketSellerTwoPickBundle:ContractRestSecured"
    name_prefix:  api_secured_

